parameters:
  database_driver: pdo_mysql
  database_host: localhost
  database_port: null
  database_name: symfony
  database_user: symfony
  database_password: null
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  locale: en
  secret: 63bc858210f1b45c929ad15e24a7cb606e8dde94
  database_path: /usr/local/var/mysql/mysql.sock
